# Config.yaml
# Setup parameters for led-display
---
youtube:
    channel_id: ''
    api_key: ''
led:
    pin: 18
    count: 256
    brightness: 10
    frequency: 800000
    inverted: false
    channel: 0
    dma: 10
